on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/validate.yml'
      - 'ExperimentalDesign.md'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/validate.yml'
      - 'ExperimentalDesign.md'

name: Validate task view

jobs:
  validate-ctv:
    runs-on: ubuntu-latest
    container:
      image: rocker/r2u:latest
    steps:
      - uses: cran-task-views/ctv/validate-ctv@main
